name: contact
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^6.5.3
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8


  cloud_firestore: any

  firebase_storage: any

  http: any

  # ✅ 원래 사용하던 tflite_v2 패키지로 복원
  tflite_v2: ^1.0.0
  # tflite_flutter: ^0.10.4

  path_provider: ^2.0.15 
  path: ^1.9.0
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4

  # ✅ Firebase 및 UUID 패키지 추가0
  firebase_core: ^3.0.0
  uuid: ^4.0.0

  # ✅ 디바이스 정보 수집용 패키지
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  dio: ^5.4.3+1

  intl: ^0.19.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/best_efficientnet_v13.tflite
    - assets/best_efficientnet_v13_labels.txt

flutter_native_splash:
  color: "#448AFF"
